package com.shen.joke.app.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.shen.joke.model.Joke;
import com.shen.joke.model.User;
import com.shen.joke.model.History;

import com.shen.joke.app.db.JokeDao;
import com.shen.joke.app.db.UserDao;
import com.shen.joke.app.db.HistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig jokeDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig historyDaoConfig;

    private final JokeDao jokeDao;
    private final UserDao userDao;
    private final HistoryDao historyDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        jokeDaoConfig = daoConfigMap.get(JokeDao.class).clone();
        jokeDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        historyDaoConfig = daoConfigMap.get(HistoryDao.class).clone();
        historyDaoConfig.initIdentityScope(type);

        jokeDao = new JokeDao(jokeDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        historyDao = new HistoryDao(historyDaoConfig, this);

        registerDao(Joke.class, jokeDao);
        registerDao(User.class, userDao);
        registerDao(History.class, historyDao);
    }
    
    public void clear() {
        jokeDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        historyDaoConfig.clearIdentityScope();
    }

    public JokeDao getJokeDao() {
        return jokeDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public HistoryDao getHistoryDao() {
        return historyDao;
    }

}
